server:
  port: 8081

spring:
  application:
    name: resetu-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/resetu_db_dev
    username: resetu_user
    password: resetu_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    enabled: true

# Permitir CORS desde Vite (5173) y otros entornos comunes
app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:3000,http://localhost:19006,http://localhost:19000
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization,X-Total-Count
    allow-credentials: true
    max-age: 3600

jwt:
  secret: dev-super-secret-key-change-it
  expiration: 3600000 # 1h en ms

logging:
  level:
    com.utec.resetu: DEBUG
    org.springframework.security: DEBUG
